name: Expense Tracker CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    services:
      # MongoDB service container for integration tests
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        if [ -f requirements-test.txt ]; then
          pip install -r requirements-test.txt
        fi
    
    - name: Lint with flake8
      continue-on-error: true  # Don't fail the build if linting fails initially
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      run: |
        # Run the tests from project root to ensure imports work correctly
        python -m pytest tests/

  verify-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install frontend dependencies
      run: |
        if [ -f "frontend/package.json" ]; then
          cd frontend
          npm install
        fi
    
    - name: Run linting
      run: |
        cd frontend
        npm run lint
    
    - name: Verify frontend builds successfully
      run: |
        cd frontend
        npm run build